<div id="Help" class="Help" align="center">
<p>
<table cellspacing="0" cellpadding="1" border="0">
<tr>
	<td bgcolor="#<%=g_arColor(3)%>">
	<font face="<%=g_arFont(1)%>" size=2>
	<b>Help</b></font></td>
	
	<td align="right" bgcolor="#<%=g_arColor(3)%>">
	<a href="#" onClick="javascript:viewHelp(); return false;">
	<img src="./images/icon_min.gif" width="16" height="14" alt="Close Help" border="0"></a>
	</td>
<tr>
	<td bgcolor="#<%=g_arColor(0)%>" colspan="2">
	<font face="<%=g_arFont(0)%>" size=2>